[application]
name = "controller"
default_platform = "desktop"
asset_dir = "assets"
public_dir = "public"



[web.app]

# HTML title tag content
title = "controller-weight"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
# Identificador estilo "dominio al revés"
identifier = "com.andra.controller_weight"

# El “publisher” que te está pidiendo el error
publisher = "Andra"
resources = ["assets/**"]
icon = ["assets/header.svg"]